language: node_js
node_js:
  - '12'
services:
  - mongodb
install: 
  - npm install -g serverless
  - npm install
script:
  - npm test
deploy:
  skip_cleanup : true
  provider: script
  script: serverless deploy
  on:
    branch: main
  
